version: "3.8"

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back
    ports:
      - "8000:8000"
    volumes:
      - ./back:/var/www/html
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=expenses
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db
    networks:
      - siview_net

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "8080:80"
    depends_on:
      - back
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    volumes:
      - ./front:/app
    networks:
      - siview_net

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: siview
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - siview_net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
  

networks:
  siview_net:
    driver: bridge