version: "3.8"

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
    volumes:
      - ./back:/var/www/html
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=siview_db
      - DB_PORT=3306
      - DB_DATABASE=siview
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - siview_db
    networks:
      - siview_net

<<<<<<< HEAD
  front:
    container_name: my_frontend
    image: node:lts
    working_dir: /var/www/html/app
    ports:
      - 8080:8080
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
    volumes:
      - ./front:/var/www/html/app
    depends_on:
      - back
    networks:
      - siview_net
        
=======
  # front:
  #   build:
  #     context: ./front
  #     dockerfile: Dockerfile
  #   container_name: front
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - back
  #   environment:
  #     - NODE_TLS_REJECT_UNAUTHORIZED=0
  #   volumes:
  #     - ./front:/app
  #   networks:
  #     - siview_net

>>>>>>> parent of bc8450a (Final global projet)
  siview_db:
    image: mysql:8.0
    container_name: siview_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: siview
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - siview_net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: siview_db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - siview_db
    networks:
      - siview_net

volumes:
  db_data:
  
networks:
  siview_net:
    driver: bridge